name: S3 Sync Example

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  s3-sync:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      # EXAMPLE: Download data from S3 bucket to a local folder `data-from-s3`
      - name: Download data from S3
        run: |
          mkdir -p data-from-s3
          aws s3 sync s3://your-bucket/data/ ./data-from-s3/

      # EXAMPLE: Upload folder `data-to-s3` to S3 bucket
      - name: Upload data to S3
        run: |
          if [ -d "data-to-s3" ]; then
            aws s3 sync ./data-to-s3/ s3://your-bucket/upload/
          else
            echo "No data-to-s3 directory to upload."
          fi
