name: S3 Sync via OIDC

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  s3-sync:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::422940799427:role/GitHub
          aws-region: us-east-1

      - name: Download from S3
        run: aws s3 sync s3://your-bucket/data ./data-from-s3

      - name: Upload to S3
        run: aws s3 sync ./data-to-s3 s3://your-bucket/upload
